### ISSUE TITLE
нет цифр для авторизации через telegram

### ISSUE THREAD

**Issue by dshevtsov** [povesma/UkrYama-2#25]
как неавторизированый пользователь захожу на страницу http://ukryama.com/ в браузере Firefox 40.0.3 и не вижу цифр для авторизации через telegram.

**Comment by povesma** [comment]
Firefox до какой-то версии не поддерживал websocket
https://developer.mozilla.org/en-US/docs/Web/API/WebSocket

Нужно выяснить, поддерживает ли именно эта версия WebSockets
