### ISSUE TITLE
не работает трекинг даты доставки письма

### ISSUE THREAD

**Issue by dshevtsov** [povesma/UkrYama-2#26]
Например: http://ukryama.com/4472/
"Статус доставки у УДАІ ГУМВС України в м. Києві  Ще не доставлено"

**Comment by dshevtsov** [comment]
пока не работает трекинг можно добавлять трек-номер в письмо тому кто оплатил яму и автору ямы. Текст: "Какое-то время дату доставки не получится посмотреть по техническим причинам. Но вы можете в любой момент проверить статус вашей заявки [здесь](http://services.ukrposhta.ua/bardcodesingle/DownloadInfo.aspx?id=0408025298321), или введите эти цифры **0408025298321** [здесь](http://services.ukrposhta.ua/bardcodesingle/)."

**Comment by dshevtsov** [comment]
2. или можно выводить трекинговый номер вместо "Ще недоставлено"
3. или заменить всё поле на |Номер для перевірки статусу листа на [сайті УкрПошти](http://services.ukrposhta.ua/bardcodesingle/)|12345678901|

**Comment by povesma** [comment]
Отличный выход

**Comment by povesma** [comment]
Работает.
