### ISSUE TITLE
Настройка среды для разработчика

### ISSUE THREAD

**Issue by Mak-Di** [povesma/UkrYama-2#34]
Всем привет!
Есть несоклько вопросов по проекту:
1. Где можно посмотреть на требования к ПО?
2. Имеется ли инструкция по установке/настройке проекта, кроме мануала на en по заливке базы?

**Comment by povesma** [comment]
Рабочая ветка - https://github.com/povesma/UkrYama-2/tree/2.3
Соответственно - https://github.com/povesma/UkrYama-2/blob/2.3/README.md

**Comment by Mak-Di** [comment]
@povesma спасибо за ответ к вопросу №2.
А что по поводу версий ПО? На какой версии это все работает, чтобы не получилось, что на среде разработчика все ок, а после деплоя на продакшен не работает.

**Comment by povesma** [comment]
2. Завантажте Yii Framework 1.1.x і розпакуйте у директорію вище проекту
+MySQL любой разумной версии
Других требований вроде бы как нет.

**Comment by poremchuk** [comment]
Внести настройки в кофиг-файл не забудьте.

**Comment by Mak-Di** [comment]
Есть большая разница между php 5.1 и 5.6 или же 7.1 и это важно.
С MySQL таже ситуация.
---------------------------------------
И еще вопрос. Как насчет хранить самую свежую версию (dev) в ветке мастер?

**Comment by poremchuk** [comment]
PHP 5.6.
Как БД можно взять последюю MariaDB

**Comment by Mak-Di** [comment]
@poremchuk спасибо, то что нужно.
Что думаете насчет хранения самого свежего кода в ветке мастер, т.е. как принято в большинстве проектов?

**Comment by poremchuk** [comment]
Думаю - это хорошая идея. Г-н @povesma идеолог проекта, ему и решать.

**Comment by Mak-Di** [comment]
И сразу последний вопрос в рамках этого тикета, что думаете по поводу использования [композера](https://getcomposer.org/)?

**Comment by poremchuk** [comment]
В Yii2 composer используеться во всю. Здесь же другая идеология, я бы его не винтил в этот проект.

**Comment by Mak-Di** [comment]
Ок, будет по чуть-чуть двигаться :)

**Comment by povesma** [comment]
Для этого проекта принципиальной разницы нет, но для определенности пусть будет MySQL 5.6
Хранение последней версии в Master - зачем? Сейчас все работает, какие преимущества даст это изменение?

**Comment by Mak-Di** [comment]
>> какие преимущества даст это изменение
Пример: Появилась идея и начинаем реализацию идеи, задача на 30 часов. 
Сделали в ветке 2.3.
Посмотрели на код, вроде все ок, приняли.
Развернули на тестовом сервере и тестируем...
На продакшене нашли ошибку, которую нужно срочно сейчас исправить.
Какие действия будут?

**Comment by povesma** [comment]
> Пример: Появилась идея и начинаем реализацию идеи, задача на 30 часов.
Сделали ветку 2.4, в которой делаем этот функционал :-)
Ошибку в продакшне фиксим в 2.3
Потом все мерджим в мастер. В мастере будет рабочая и стабильная версия.
НО!
Пока что keep it simple stupid, так как нормальную систему деплоймента и поддержки еще предстоит сделать (при наличии ресурсов)

**Comment by poremchuk** [comment]
По моему опыту develpment flow волонтерских проектов или легкий или проекта вообще не будет.

**Comment by Mak-Di** [comment]
@povesma , ок
Появилась идея и начинаем реализацию идеи, задача на 30 часов.
Создаю ветку 2.4 от 2.3 и начинаю реализацию..
Еще одна идея пришла, так же начинаем реализацию.. 2.5 от 2.3
...
Еще можно парочку добавить, а потом девы пропали/нет времени, а уже имеем
2.3
2.4
2.5
2.X
......
Я к чему клоню-то. Есть мировая практика, если посмотреть в любой опен-сорс проект, то в ветке master - всега последний не стабильный код. Поправьте, если есть исключения.

**Comment by Mak-Di** [comment]
>> По моему опыту develpment flow волонтерских проектов или легкий или проекта вообще не будет.
:+1: 
Флоу должен быть понятым и работоспособным.

**Comment by povesma** [comment]
Будет код - будут бренчи :-) . Ответственность за баги и стабильность работы сервиса беру на себя.
На имеющихся объемах нового кода любой вариант будет хорошо работать. Будет много нового кода - будем принимать решения (CI и другие прелести).

**Comment by Mak-Di** [comment]
@povesma любую новую фичу начинаем делать от 2.3 (на данный момент), верно?

**Comment by povesma** [comment]
Да. Я 2.3 сейчас смерджу с master

2017-03-30 2:35 GMT+13:00 Mak-Di <notifications@github.com>:

**Comment by Mak-Di** [comment]
Все понял, спасибо за разъяснения!
