### ISSUE TITLE
После ремонта дороги

### ISSUE THREAD

**Issue by Mak-Di** [povesma/UkrYama-2#35]
Указанный участок был отремонтирован.
Где и как можно это отметить и добавить фото?

**Comment by povesma** [comment]
Отметить исправление сейчас может тот, кто отправил заявление. Предполагаем, что без отправленого заявления ничего не исправится :-)
TODO: сделать, чтобы отметить исправление мог автор ямы, а любой зарегистрированный пользователь мог отметить исправление с модерацией администратором.

**Comment by Mak-Di** [comment]
:+1:

**Comment by povesma** [comment]
Готово. e94c1097be33ed0263cc4c9b7f205fe6a68fd88a

**Comment by dim-ash** [comment]
судя по истории, эту задачу можно закрывать
